In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [ ]:
df=pd.read_csv('/content/house_prices.csv')

In [ ]:
df.head()

,sqft_living,bedrooms,bathrooms,floors,house_age,dist_to_city_km,quality_score,price
0,959,4,2.0,2.0,10,13.97,6,256153
1,3173,4,2.6,2.0,9,1.40,4,602494
2,2017,1,1.9,1.0,71,0.24,9,403973
3,818,5,3.7,1.5,45,13.07,3,208514
4,2036,3,2.3,2.0,57,1.90,5,396980

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.describe()

,sqft_living,bedrooms,bathrooms,floors,house_age,dist_to_city_km,quality_score,price
count,1000.000000,1000.000000,988.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,1872.225000,3.368000,2.528745,1.621500,19.530000,8.020810,6.581000,4.081768e+05
std,721.658094,1.189955,0.963300,0.613077,18.964882,7.635918,2.240638,1.518990e+05
min,450.000000,1.000000,1.000000,1.000000,0.000000,0.200000,3.000000,8.956100e+04
25%,1362.000000,3.000000,1.800000,1.000000,6.000000,2.327500,5.000000,3.257180e+05
50%,1873.500000,3.000000,2.500000,1.500000,13.000000,5.690000,7.000000,4.020970e+05
75%,2358.000000,4.000000,3.100000,2.000000,27.000000,11.495000,9.000000,4.792382e+05
max,3927.000000,6.000000,5.000000,3.000000,100.000000,46.160000,10.000000,2.558280e+06

In [ ]:
df.isnull().sum()

sqft_living         0
bedrooms            0
bathrooms          12
floors              0
house_age           0
dist_to_city_km     0
quality_score       0
price               0
dtype: int64

In [ ]:
df['bathrooms']=df['bathrooms'].fillna(df['bathrooms'].median())
df.isnull().sum()

sqft_living        0
bedrooms           0
bathrooms          0
floors             0
house_age          0
dist_to_city_km    0
quality_score      0
price              0
dtype: int64

In [ ]:
q1=df['price'].quantile(0.25)
q3=df['price'].quantile(0.75)
iqr=q3-q1
upper=q3+1.5*iqr
df=df[df['price']<upper]
df.shape

(993, 8)

In [ ]:
x=df.drop(columns='price')
y=df['price']

In [ ]:
print(x)

     sqft_living  bedrooms  bathrooms  floors  house_age  dist_to_city_km  \
0            959         4        2.0     2.0         10            13.97
1           3173         4        2.6     2.0          9             1.40
2           2017         1        1.9     1.0         71             0.24
3            818         5        3.7     1.5         45            13.07
4           2036         3        2.3     2.0         57             1.90
..           ...       ...        ...     ...        ...              ...
995         2530         2        1.5     2.0          2             6.32
996         1159         3        2.1     2.5         12             1.00
997         2530         3        2.1     1.5         37             3.36
998          785         1        1.0     3.0          4             0.77
999         3076         3        2.2     2.0         19             5.67

     quality_score
0                6
1                4
2                9
3                3
4                5
..             ...
995              3
996              5
997              9
998              5
999              6

[993 rows x 7 columns]

In [ ]:
print(y)

0      256153
1      602494
2      403973
3      208514
4      396980
        ...
995    442706
996    290977
997    512494
998    242206
999    574995
Name: price, Length: 993, dtype: int64

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(x)
x_std=scaler.transform(x)

In [ ]:
print(x_std)

[[-1.27005373  0.53184711 -0.54995639 ... -0.50463434  0.77541051
  -0.25823263]
 [ 1.83426726  0.53184711  0.07547598 ... -0.55729322 -0.86770085
  -1.15325883]
 [ 0.21340228 -1.98702816 -0.65419511 ...  2.70755733 -1.01933244
   1.08430666]
 ...
 [ 0.93269617 -0.30777798 -0.44571766 ...  0.91715542 -0.61149574
   1.08430666]
 [-1.51402475 -1.98702816 -1.59234366 ... -0.82058762 -0.95005249
  -0.70574573]
 [ 1.69826042 -0.30777798 -0.34147893 ... -0.03070442 -0.30953971
  -0.25823263]]

In [ ]:
x=x_std

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(993, 7) (794, 7) (199, 7)

In [ ]:
cf=RandomForestRegressor(n_estimators=200,max_depth=10,random_state=2)

In [ ]:
cf.fit(x_train,y_train)

RandomForestRegressor(max_depth=10, n_estimators=200, random_state=2)

In [ ]:
x_train_pred=cf.predict(x_train)

In [ ]:
x_train_r2=r2_score(y_train,x_train_pred)

In [ ]:
print(x_train_r2)

0.9908600329907643

In [ ]:
print(x_train_r2)

0.9908600329907643

In [ ]:
data=[2150,3,2.0,2.0,8,5.4,7]
print(data)

[2150, 3, 2.0, 2.0, 8, 5.4, 7]

In [ ]:
data_np=np.asarray(data)
print(data_np)

[2.15e+03 3.00e+00 2.00e+00 2.00e+00 8.00e+00 5.40e+00 7.00e+00]

In [ ]:
data_reshape=data_np.reshape(1,-1)

In [ ]:
input_std=scaler.transform(data_reshape)

In [ ]:
print(input_std)

[[2.15e+03 3.00e+00 2.00e+00 2.00e+00 8.00e+00 5.40e+00 7.00e+00]]

In [ ]:
pred=cf.predict(input_std)
print(pred)

[568384.885]