In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [ ]:
df=pd.read_csv('/content/winequality.csv')

In [ ]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,8.94,0.507,0.29,0.90,0.031,7.8,21.9,0.9993,3.44,0.62,9.89,5
1,8.42,0.681,0.19,3.33,0.012,1.0,53.6,0.9953,3.36,1.10,11.77,6
2,9.65,0.362,0.35,2.24,0.159,21.4,62.2,0.9968,3.46,0.68,9.69,5
3,5.63,0.278,0.50,0.90,0.099,6.3,19.1,0.9952,3.50,0.72,10.90,6
4,6.49,0.474,0.59,6.77,0.142,19.3,44.9,0.9972,3.41,0.67,11.01,5

In [ ]:
df.shape

(1607, 12)

In [ ]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1607.000000,1607.000000,1607.000000,1607.000000,1595.000000,1607.000000,1607.000000,1607.000000,1592.000000,1588.000000,1607.000000,1607.000000
mean,8.291077,0.525606,0.282215,2.614051,0.091024,17.093404,47.845240,0.996706,3.319604,0.668734,10.438419,5.589297
std,1.682200,0.176942,0.179063,2.323494,0.044608,10.122153,21.154736,0.001824,0.150891,0.165679,1.072897,0.716700
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,2.000000,0.991100,2.780000,0.330000,8.400000,4.000000
25%,7.150000,0.407000,0.150000,0.900000,0.059000,9.100000,32.850000,0.995500,3.220000,0.550000,9.660000,5.000000
50%,8.290000,0.521000,0.270000,1.730000,0.090000,16.800000,47.000000,0.996700,3.320000,0.670000,10.410000,6.000000
75%,9.430000,0.639000,0.410000,3.285000,0.121000,24.100000,62.000000,0.997900,3.420000,0.780000,11.170000,6.000000
max,15.360000,1.075000,0.860000,15.500000,0.235000,53.200000,116.700000,1.001900,3.810000,1.210000,14.340000,8.000000

In [ ]:
df.isnull().sum()

fixed acidity            0
volatile acidity         0
citric acid              0
residual sugar           0
chlorides               12
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                      15
sulphates               19
alcohol                  0
quality                  0
dtype: int64

In [ ]:
df['fixed acidity']= df['fixed acidity'].fillna(df['fixed acidity'].median())
df.isnull().sum()

fixed acidity            0
volatile acidity         0
citric acid              0
residual sugar           0
chlorides               12
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                      15
sulphates               19
alcohol                  0
quality                  0
dtype: int64

In [ ]:

q1=df['quality'].quantile(0.25)
q3=df['quality'].quantile(0.75)
iqr=q3-q1
upper=q3+q3*iqr
df=df[(df['quality']<=upper)]
df.shape

(1607, 12)

In [ ]:
x = df.drop(columns="quality")
y = df["quality"]

In [ ]:
print(x)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0              8.94             0.507         0.29            0.90      0.031
1              8.42             0.681         0.19            3.33      0.012
2              9.65             0.362         0.35            2.24      0.159
3              5.63             0.278         0.50            0.90      0.099
4              6.49             0.474         0.59            6.77      0.142
...             ...               ...          ...             ...        ...
1602           8.80             0.721         0.17            2.47      0.012
1603           8.97             0.492         0.26            1.43      0.149
1604           9.57             0.773         0.12            0.90      0.142
1605           5.92             0.344         0.11            5.88      0.111
1606           7.51             0.535         0.44            0.90      0.060

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                     7.8                  21.9   0.9993  3.44       0.62
1                     1.0                  53.6   0.9953  3.36       1.10
2                    21.4                  62.2   0.9968  3.46       0.68
3                     6.3                  19.1   0.9952  3.50       0.72
4                    19.3                  44.9   0.9972  3.41       0.67
...                   ...                   ...      ...   ...        ...
1602                  7.0                  37.1   0.9966  3.42       0.45
1603                 16.5                  47.4   0.9972  3.47       0.68
1604                 13.5                  37.1   0.9961  3.52       0.59
1605                 10.8                  37.6   0.9948  3.35       0.75
1606                 23.9                  43.3   1.0002  3.04       0.97

      alcohol
0        9.89
1       11.77
2        9.69
3       10.90
4       11.01
...       ...
1602    10.60
1603    11.69
1604     9.20
1605     8.73
1606    10.26

[1607 rows x 11 columns]

In [ ]:
print(y)

0       5
1       6
2       5
3       6
4       5
       ..
1602    6
1603    6
1604    5
1605    5
1606    6
Name: quality, Length: 1607, dtype: int64

In [ ]:
scaler = StandardScaler()
x_std = scaler.fit_transform(x)

In [ ]:
print(x_std)

[[ 0.38587883 -0.10518648  0.0434882  ...  0.79815144 -0.29424217
  -0.51131685]
 [ 0.07666364  0.87849356 -0.51514918 ...  0.26779944  2.6038474
   1.24149431]
 [ 0.80807649 -0.92491985  0.37867062 ...  0.93073944  0.06801903
  -0.69778612]
 ...
 [ 0.76050492  1.39860026 -0.90619534 ...  1.32850344 -0.47537277
  -1.15463584]
 [-1.40994785 -1.02667986 -0.96205908 ...  0.20150544  0.49065709
  -1.59283862]
 [-0.46446294  0.05310686  0.88144426 ... -1.85360856  1.81894814
  -0.16634869]]

In [ ]:
x=x_std

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(1607, 11) (1285, 11) (322, 11)

In [ ]:
cf = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    random_state=2
)

In [ ]:
cf.fit(x_train, y_train)

RandomForestRegressor(max_depth=10, n_estimators=200, random_state=2)

In [ ]:

x_train_pred=cf.predict(x_train)

In [ ]:
x_train_r2 = r2_score(y_train, x_train_pred)

In [ ]:
print("Training R2 Score:", x_train_r2)

Training R2 Score: 0.8003861362180429

In [ ]:
x_test_pred=cf.predict(x_test)
x_test_r2=r2_score(y_test,x_test_pred)
print(x_test_r2)

0.25860192464920584

In [ ]:
data = [8.94,0.507,0.29,1.09,0.045,30.8,85.4,0.99732,3.36,0.62,9.89]

data = np.asarray(data)

data_reshape = data.reshape(1,-1)

input_std = scaler.transform(data_reshape)

pred = cf.predict(input_std)

print("Predicted Wine Quality:", pred)

Predicted Wine Quality: [5.61923797]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(