In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
df=pd.read_csv('/content/heart_disease.csv')

In [ ]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,42,male,0,94.0,310.5,1,0,179.4,0,1.85,2,2,1,0
1,31,Female,2,116.9,248.6,0,0,153.5,1,1.99,1,0,2,0
2,64,Male,3,133.3,260.9,0,1,136.8,0,0.07,2,0,2,1
3,58,male,0,124.4,229.7,0,0,173.9,0,1.68,1,2,1,0
4,45,Female,1,148.8,258.7,0,0,186.3,1,1.16,1,2,2,0

In [ ]:
df.describe()

,age,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,500.00000,500.000000,495.000000,490.000000,500.000000,500.000000,493.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,53.52800,0.938000,131.196566,243.353061,0.156000,0.510000,148.295538,0.326000,1.013400,1.422000,0.750000,2.326000,0.404000
std,9.36058,1.008062,16.790346,51.225905,0.363219,0.512274,22.668989,0.469217,1.008851,0.607168,1.055333,0.579997,0.491189
min,29.00000,0.000000,94.000000,126.000000,0.000000,0.000000,85.700000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,47.00000,0.000000,119.250000,209.950000,0.000000,0.000000,131.800000,0.000000,0.230000,1.000000,0.000000,2.000000,0.000000
50%,54.00000,1.000000,131.200000,244.300000,0.000000,1.000000,148.300000,0.000000,0.685000,1.000000,0.000000,2.000000,0.000000
75%,60.00000,2.000000,142.250000,277.200000,0.000000,1.000000,163.100000,1.000000,1.422500,2.000000,1.000000,3.000000,1.000000
max,77.00000,3.000000,183.200000,376.600000,1.000000,2.000000,202.000000,1.000000,5.650000,2.000000,4.000000,3.000000,1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       500 non-null    int64
 1   sex       500 non-null    object
 2   cp        500 non-null    int64
 3   trestbps  495 non-null    float64
 4   chol      490 non-null    float64
 5   fbs       500 non-null    int64
 6   restecg   500 non-null    int64
 7   thalach   493 non-null    float64
 8   exang     500 non-null    int64
 9   oldpeak   500 non-null    float64
 10  slope     500 non-null    int64
 11  ca        500 non-null    int64
 12  thal      500 non-null    int64
 13  target    500 non-null    int64
dtypes: float64(4), int64(9), object(1)
memory usage: 54.8+ KB

In [ ]:
df.shape

(500, 14)

In [ ]:
print(df['target'].value_counts())

target
0    298
1    202
Name: count, dtype: int64

In [ ]:
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])

In [ ]:

X = df.drop('target', axis=1)
y = df['target']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy * 100, 2), "%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 63.0 %

Classification Report:
              precision    recall  f1-score   support

           0       0.65      0.78      0.71        58
           1       0.58      0.43      0.49        42

    accuracy                           0.63       100
   macro avg       0.62      0.60      0.60       100
weighted avg       0.62      0.63      0.62       100

In [ ]:
new_patient = [[45, 0, 1, 130, 250, 0, 1, 150, 0, 1.2, 1, 0, 2]]
prediction = model.predict(new_patient)

if prediction[0] == 1:
    print("\nHeart Disease Detected")
else:
    print("\nNo Heart Disease Detected")

No Heart Disease Detected

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(